services:
  docs:
    image: pycon_portugal_2026_local_docs
    container_name: pycon_portugal_2026_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./pycon_portugal_2026:/app/pycon_portugal_2026:z
    ports:
      - '9000:9000'
    command: /start-docs
